import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:lantransfer_mobile/src/crypto.dart';
import 'package:lantransfer_mobile/src/platform_crypto.dart';

/// Cross-platform crypto interop.
///
/// This suite loads the SAME pinned vectors as the desktop Vitest interop test
/// (desktop/src/shared/interop.test.ts), generated by WebCrypto. It proves the
/// Flutter client can:
///   1. reconstruct the pinned P-256 private key,
///   2. import the peer's SPKI public key (hand-rolled prefix + WebCrypto's
///      must agree),
///   3. derive the identical AES-256-GCM session key, and
///   4. open() a WebCrypto-sealed `nonce||ciphertext||tag` frame to the exact
///      expected plaintext — in both directions.
///
/// If the SPKI prefix, HKDF salt/info, or the frame layout ever diverge between
/// the platforms, this test fails on CI — turning "a phone pairs with a laptop"
/// from an assertion into a verified guarantee.
void main() {
  final vectors = _loadVectors();

  Uint8List b64u(String s) {
    final pad = (4 - s.length % 4) % 4;
    return base64Url.decode(s + '=' * pad);
  }

  // JWK base64url coordinates are already url-safe, unpadded.
  List<int> coord(Map<String, dynamic> jwk, String k) => b64u(jwk[k] as String);

  group('cross-platform interop', () {
    test('imports the WebCrypto SPKI public key and derives the pinned session key (A -> B)',
        () async {
      final aJwk = (vectors['peerA'] as Map)['privateJwk'] as Map<String, dynamic>;
      final agreement = await EcdhKeyAgreement.fromKeyPairData(
        coord(aJwk, 'd'),
        coord(aJwk, 'x'),
        coord(aJwk, 'y'),
      );

      // Re-derive our own SPKI from the pinned coordinates and confirm it
      // matches the reference SPKI byte-for-byte (validates the hand-rolled
      // 26-byte prefix + uncompressed-point encoding).
      expect(agreement.publicKeyB64, equals((vectors['peerA'] as Map)['spkiB64Url']));

      final peerSpki = (vectors['peerB'] as Map)['spkiB64Url'] as String;
      final cipher = await agreement.deriveCipher(peerSpki);

      // Open the WebCrypto-sealed frame with the Dart-derived session cipher.
      final opened = await cipher.open(vectors['sealedFrameB64Url'] as String);
      expect(opened, equals(vectors['expectedPlaintext']));
    });

    test('derives the identical session key in the mirror direction (B -> A)', () async {
      final bJwk = (vectors['peerB'] as Map)['privateJwk'] as Map<String, dynamic>;
      final agreement = await EcdhKeyAgreement.fromKeyPairData(
        coord(bJwk, 'd'),
        coord(bJwk, 'x'),
        coord(bJwk, 'y'),
      );
      expect(agreement.publicKeyB64, equals((vectors['peerB'] as Map)['spkiB64Url']));

      final peerSpki = (vectors['peerA'] as Map)['spkiB64Url'] as String;
      final cipher = await agreement.deriveCipher(peerSpki);
      final opened = await cipher.open(vectors['sealedFrameB64Url'] as String);
      expect(opened, equals(vectors['expectedPlaintext']));
    });

    test('a Dart-sealed binary frame opens under the same session key', () async {
      final aJwk = (vectors['peerA'] as Map)['privateJwk'] as Map<String, dynamic>;
      final agreement = await EcdhKeyAgreement.fromKeyPairData(
        coord(aJwk, 'd'),
        coord(aJwk, 'x'),
        coord(aJwk, 'y'),
      );
      final cipher = await agreement.deriveCipher(
        (vectors['peerB'] as Map)['spkiB64Url'] as String,
      );

      // Seal a binary chunk frame the way the transfer engine does, then open
      // it back — exercising sealBytes/openBytes round-trip on the mobile side.
      final payload = Uint8List.fromList(List<int>.generate(1000, (i) => (i * 7 + 3) & 0xff));
      final frame = encodeChunkFrame(ChunkFrame('00112233445566778899aabbccddeeff', 1, true, payload));
      final sealed = await cipher.sealBytes(frame);
      final plain = await cipher.openBytes(sealed);
      final decoded = decodeChunkFrame(plain)!;
      expect(decoded.transferId, equals('00112233445566778899aabbccddeeff'));
      expect(decoded.seq, equals(1));
      expect(decoded.last, isTrue);
      expect(decoded.data, equals(payload));
    });
  });
}

Map<String, dynamic> _loadVectors() {
  // The vectors live at <repo>/shared/interop/interop-vectors.json, shared with
  // the desktop client. Tests run from the mobile/ package root.
  final candidates = [
    '../shared/interop/interop-vectors.json',
    'shared/interop/interop-vectors.json',
  ];
  for (final path in candidates) {
    final f = File(path);
    if (f.existsSync()) {
      return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    }
  }
  throw StateError('interop-vectors.json not found (looked in: $candidates)');
}
