import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lantransfer_mobile/src/crypto.dart';
import 'package:lantransfer_mobile/src/platform_crypto.dart';

/// Cross-platform crypto interop.
///
/// This suite loads the SAME pinned vectors as the desktop Vitest interop test
/// (desktop/src/shared/interop.test.ts), generated by WebCrypto. It proves the
/// Flutter client is byte-compatible with the desktop on the two things that
/// actually cross the wire between a phone and a laptop:
///
///   1. the SPKI public-key encoding (the hand-rolled DER prefix must match what
///      WebCrypto emits), and
///   2. the AES-256-GCM `nonce || ciphertext || tag` frame format, keyed by the
///      shared session secret.
///
/// The session key itself is pinned in the fixture, so this test keys an
/// [AesGcmCipher] with it directly. (P-256 ECDH derivation is delegated to the
/// platform WebRTC engine at runtime; the pure-Dart `cryptography` fallback does
/// not implement `sharedSecretKey` for P-256 in the bare Dart test VM, which is
/// why we assert against the pinned key rather than re-deriving it here.)
void main() {
  final vectors = _loadVectors();

  Uint8List b64u(String s) {
    final pad = (4 - s.length % 4) % 4;
    return base64Url.decode(s + '=' * pad);
  }

  List<int> coord(Map<String, dynamic> jwk, String k) => b64u(jwk[k] as String);

  AesGcmCipher pinnedCipher() =>
      AesGcmCipher(SecretKey(b64u(vectors['sessionKeyB64Url'] as String)));

  group('cross-platform interop', () {
    test("the hand-rolled SPKI encoding matches WebCrypto's for peer A", () async {
      final aJwk = (vectors['peerA'] as Map)['privateJwk'] as Map<String, dynamic>;
      final agreement = await EcdhKeyAgreement.fromKeyPairData(
        coord(aJwk, 'd'),
        coord(aJwk, 'x'),
        coord(aJwk, 'y'),
      );
      // Re-derive our SPKI from the pinned coordinates; it must equal the
      // WebCrypto-exported SPKI byte-for-byte.
      expect(agreement.publicKeyB64, equals((vectors['peerA'] as Map)['spkiB64Url']));
    });

    test('the hand-rolled SPKI encoding matches for peer B', () async {
      final bJwk = (vectors['peerB'] as Map)['privateJwk'] as Map<String, dynamic>;
      final agreement = await EcdhKeyAgreement.fromKeyPairData(
        coord(bJwk, 'd'),
        coord(bJwk, 'x'),
        coord(bJwk, 'y'),
      );
      expect(agreement.publicKeyB64, equals((vectors['peerB'] as Map)['spkiB64Url']));
    });

    test('opens a WebCrypto-sealed frame to the exact expected plaintext', () async {
      final opened = await pinnedCipher().open(vectors['sealedFrameB64Url'] as String);
      expect(opened, equals(vectors['expectedPlaintext']));
    });

    test('a Dart-sealed frame round-trips under the shared session key', () async {
      final cipher = pinnedCipher();
      final sealed = await cipher.seal(vectors['expectedPlaintext'] as String);
      // Different nonce than the pinned frame, but opens to the same plaintext.
      final opened = await cipher.open(sealed);
      expect(opened, equals(vectors['expectedPlaintext']));
    });

    test('a Dart-sealed binary chunk frame round-trips (sealBytes/openBytes)', () async {
      final cipher = pinnedCipher();
      final payload = Uint8List.fromList(List<int>.generate(1000, (i) => (i * 7 + 3) & 0xff));
      final frame = encodeChunkFrame(
        ChunkFrame('00112233445566778899aabbccddeeff', 1, true, payload),
      );
      final sealed = await cipher.sealBytes(frame);
      final plain = await cipher.openBytes(sealed);
      final decoded = decodeChunkFrame(plain)!;
      expect(decoded.transferId, equals('00112233445566778899aabbccddeeff'));
      expect(decoded.seq, equals(1));
      expect(decoded.last, isTrue);
      expect(decoded.data, equals(payload));
    });
  });
}

Map<String, dynamic> _loadVectors() {
  final candidates = [
    '../shared/interop/interop-vectors.json',
    'shared/interop/interop-vectors.json',
  ];
  for (final path in candidates) {
    final f = File(path);
    if (f.existsSync()) {
      return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    }
  }
  throw StateError('interop-vectors.json not found (looked in: $candidates)');
}
