/**
 * Regenerate the cross-platform crypto interop vectors.
 *
 *   node desktop/scripts/gen-interop.mjs > shared/interop/interop-vectors.json
 *
 * The vectors pin two ECDH P-256 key pairs, the AES-256-GCM session key both
 * peers derive from them, and a sealed `offer-file` frame with a *fixed* nonce.
 * The desktop (Vitest) and mobile (Dart) interop tests both load this file and
 * prove they can import the SPKI public keys, derive the mirror session key,
 * and open() the sealed frame to the exact expected plaintext — verifying, not
 * merely asserting, that a Dart-sealed frame decrypts under the TS open() and
 * that the hand-rolled SPKI prefix matches what WebCrypto emits.
 *
 * WebCrypto is the reference implementation; run this only when the wire format
 * intentionally changes, then commit the regenerated JSON.
 */
import { webcrypto } from 'node:crypto';

const subtle = webcrypto.subtle;
const enc = new TextEncoder();
const HKDF_INFO = 'lantransfer/v1/session-key';

function toB64Url(bytes) {
  return Buffer.from(bytes)
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

async function main() {
  const a = await subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']);
  const b = await subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']);

  // Strip key_ops/ext so the JWK is portable: importers can request whatever
  // usages they need without a "usage mismatch" DataError.
  const cleanJwk = (jwk) => {
    const { key_ops, ext, ...rest } = jwk;
    void key_ops;
    void ext;
    return rest;
  };
  const aJwk = cleanJwk(await subtle.exportKey('jwk', a.privateKey));
  const bJwk = cleanJwk(await subtle.exportKey('jwk', b.privateKey));
  const aSpki = new Uint8Array(await subtle.exportKey('spki', a.publicKey));
  const bSpki = new Uint8Array(await subtle.exportKey('spki', b.publicKey));

  const bits = await subtle.deriveBits({ name: 'ECDH', public: b.publicKey }, a.privateKey, 256);
  const hkdfKey = await subtle.importKey('raw', bits, 'HKDF', false, ['deriveKey']);
  const sessionKey = await subtle.deriveKey(
    { name: 'HKDF', hash: 'SHA-256', salt: new Uint8Array(0), info: enc.encode(HKDF_INFO) },
    hkdfKey,
    { name: 'AES-GCM', length: 256 },
    true,
    ['encrypt', 'decrypt'],
  );
  const rawSession = new Uint8Array(await subtle.exportKey('raw', sessionKey));

  const plaintext = JSON.stringify({
    t: 'offer-file',
    transferId: '00112233445566778899aabbccddeeff',
    name: 'hello.txt',
    size: 11,
    mime: 'text/plain',
  });
  const nonce = new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
  const ct = new Uint8Array(
    await subtle.encrypt({ name: 'AES-GCM', iv: nonce, tagLength: 128 }, sessionKey, enc.encode(plaintext)),
  );
  const framed = new Uint8Array(nonce.length + ct.length);
  framed.set(nonce, 0);
  framed.set(ct, nonce.length);

  const fixture = {
    _comment:
      'LanTransfer cross-platform crypto interop vectors. Generated by desktop/scripts/gen-interop.mjs using WebCrypto (the reference). The Dart client MUST import these SPKI public keys, derive the mirror AES-256-GCM session key, and open() sealedFrame to expectedPlaintext — proving byte-level desktop<->mobile interop.',
    hkdfInfo: HKDF_INFO,
    peerA: { privateJwk: aJwk, spkiB64Url: toB64Url(aSpki) },
    peerB: { privateJwk: bJwk, spkiB64Url: toB64Url(bSpki) },
    sessionKeyB64Url: toB64Url(rawSession),
    sealedFrameB64Url: toB64Url(framed),
    expectedPlaintext: plaintext,
  };

  process.stdout.write(JSON.stringify(fixture, null, 2) + '\n');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
